version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - regex-33

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - regex-33

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx:/etc/nginx/conf.d
    networks:
      - regex-33

volumes:
  wordpress:
  mariadb_data:

networks:
  regex-33:
    driver: bridge