version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - regex-33

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - redis
      - mariadb
    env_file: .env
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - regex-33

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - regex-33
    

  redis:
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: always
    depends_on:
      - mariadb 
    ports:
      - "6379:6379"
    networks:
      - regex-33
    
  ftps:
    depends_on:
      - wordpress
    build:
      context: ./requirements/ftps
      dockerfile: Dockerfile
    container_name: ftps
    restart: always
    env_file: .env
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - regex-33
  
  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - regex-33

  phpredisadmin:
    depends_on:
      - redis
    build:
      context: ./requirements/phpredisadmin
      dockerfile: Dockerfile
    container_name: phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    restart: always
    ports:
      - "8081:80"
    networks:
      - regex-33

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/regex-33/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/regex-33/data/mariadb_data

networks:
  regex-33:
    driver: bridge

